### ISSUE TITLE
sync the info about event

### ISSUE THREAD

**Issue by TymekSL** [Mehran1022mm/Event-Core#1]
**Is your feature request related to a problem? Please describe.**
There is no problem.

**Describe the solution you'd like**
I would like to have synchronizated messages in all my servers when the event will start. Meaby there is way to make this with mysql? sso sending message "EVENT HAS BEEN STARTED" for chat to all servers OR sending title like EVENT STARTED sub: Type /event join to join! 
or meaby making bungee bridge plugin to sending this message in the chat? 
2. /event - replacing this to /event help 
3. support 1.8+ 

**Describe alternatives you've considered**
.

**Additional context**

.

**Comment by Mehran1022mm** [comment]
Hello And Thanks For Contacting Me. So You Want To Send "Event Started" Message To All Servers?
If It's Your Request I Can Do It With "Bukkit & Bungeecord Messaging Channel".
Unfortunately Our Plugin Cant Support 1.8. Because Of Our GUI Manager dependency.
Maybe In Newer Version We Change The Dependency Or Something.

**Comment by Mehran1022mm** [comment]
/Event is main command. I'll add /event help soon

**Comment by TymekSL** [comment]
yes, easy message when event has been started, nice to see the title like in the example
Event
Sub: type /event join to join! 
of course, configurable (stay out, stay in too) 
Titles will working in 1.9+ , so is there way to add this versions + ?

**Comment by Mehran1022mm** [comment]
I'll add this feature in 1.0.3 version. 1.0.2 is out you can download it now from spigot. If thats the end if this conversation tell me to close it. Dont forgot to rate us 5 stars
